class Constant:
    FB_TAG_POSTBACK = 'postback'
    FB_TAG_READ = 'read'
    FB_TAG_DELIVERY = 'delivery'
    FB_QUICK_REPLY = 'quick_reply'
    FB_TAG_TEXT = 'text'
    FB_TAG_ATTACHMENTS = 'attachments'
    FB_IS_ECHO = 'is_echo'
    FB_MESSAGE = 'message'
    FB_MESSAGING = 'messaging'
    FB_ENTRY = 'entry'
    FB_STANDBY = 'standby'
    FB_ID = 'id'
    FB_PAYLOAD = 'payload'
    FB_SENDER = 'sender'
