# Generated by Django 2.2.13 on 2020-06-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('facebook_id', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('is_spammer', models.BooleanField(default=False, verbose_name='Spammer')),
                ('last_contacted_at', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageWatermarks',
            fields=[
                ('message_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('watermark', models.CharField(max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='example_bot.BotUsers')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLogs',
            fields=[
                ('message_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='example_bot.BotUsers')),
            ],
        ),
    ]
